### ISSUE TITLE
what's going on

### ISSUE THREAD

**Issue by djmin43** [steadily-worked/github-actions-playground#1]
This is supposedly a github 'actions' playground, yet I don't see any actions in the repo. Can you explain?

**Comment by steadily-worked** [comment]
i will do it tonight after work 😂

**Comment by danwsc09** [comment]
Looking forward to some good stuff in this repo 👍

**Comment by steadily-worked** [comment]
i decided to use GitHub Actions in my Gatsby Blog :(

**Comment by steadily-worked** [comment]
now i reopen this repo to just practice about it haha.

**Comment by steadily-worked** [comment]
<img width="1530" alt="스크린샷 2023-02-14 오전 12 42 31" src="https://user-images.githubusercontent.com/61453718/218503775-4e985c3e-b163-4024-a2a7-c93764c38b7c.png">
can someone tell me why this error happens?

**Comment by steadily-worked** [comment]
<img width="497" alt="스크린샷 2023-02-16 오후 10 26 25" src="https://user-images.githubusercontent.com/61453718/219377179-8a899562-d4b4-47e2-bfa4-94d3cfe5442d.png">

finally i made it that's because project folder is in two depth.
